### PR TITLE
Make go swish work again

### PR DESCRIPTION
**Pull request by ptomasroos**
The test certs are outdated
The return types from the api has changed when the endpoints were updated? Because number can't be deserialized into a string according to the json unmarshal, this causes the example/main.go to fail

### CODE REVIEW

**Comment by frozzare** [comment]
Can you answer this @HaraldNordgren? I haven’t used this package in a while.

**Comment by ptomasroos** [comment]
Without cert change, create request fails with

```
Post https://mss.cpc.getswish.net/swish-cpcapi/api/v1/paymentrequests: x509: certificate signed by unknown authority
```

This is a example JSON being returned from the swish api.

```
{"amount":100,"callbackUrl":"https://*.ngrok.io","currency":"SEK","dateCreated":"2018-11-12T07:32:14.865Z","datePaid":"2018-11-12T07:32:18.865Z","id":"27544D0E55154DAE815CC7CF916888A1","message":"Kingston USB Flash Drive 8 GB","payeeAlias":"1231181189","payeePaymentReference":"0123456789","paymentReference":"63FF7A15C3DC4CDEAEE62DB99CD1044D","status":"PAID"}
```

**Comment by frozzare** [comment]
Will this work with the changes you made @HaraldNordgren? I sorry, but I haven't read the documentation for the new apis. Let's see what @HaraldNordgren says before mering this!

**Comment by ptomasroos** [comment]
NP. I have no rush, can always run my fork :)

**Comment by HaraldNordgren** [comment]
@ptomasroos @frozzare We ended up not using this library at all, so I cannot answer to whether the certs worked or not.

For the `amount`, we also noticed a discrepancy. Staging vs. production had different return types on the callback -- which is quite mind boggling.

**Comment by frozzare** [comment]
@ptomasroos Is that true that the staging and production has different types for amount?

**Comment by frozzare** [comment]
This package was created a long time ago before they changed there endpoints and api so it's not strange that some stuff isn't working as expected. 

I'm happy to merge this if it works and it's not creating any new issues :)

**Comment by ptomasroos** [comment]
So what did you end up using @HaraldNordgren ?

**Comment by frozzare** [comment]
Let’s discuss the pull request. This is not the right forum for discussions about other packages. If this pull fixes the issue I’m happy to merge it.

Does it works with the amount issue? Or do we need a custom type to support both environments? @ptomasroos

**Comment by ptomasroos** [comment]
I will let you know the day I hit production

**Pull request merged**
