### PR TITLE
Update base URLs

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Looking at the docs on 2018-10-20 it seems that the current URLs are:

- `https://mss.cpc.getswish.net/swish-cpcapi/api/v1` (https://developer.getswish.se/merchants-test-con/4-create-payment-request/)
- `https://cpc.getswish.net/swish-cpcapi/api/v1` (https://developer.getswish.se/merchants-api-manual/7-production-environment/)

### CODE REVIEW

**Comment by frozzare** [comment]
Looks like all tests failes, please take a look at that.

**Comment by HaraldNordgren** [comment]
@frozzare Updated.

**Comment by frozzare** [comment]
Merged https://github.com/frozzare/go-swish/commit/c13313111b27f2a923c33fa1ce6e18a34e8fd1f7, thanks @HaraldNordgren!

**Comment by HaraldNordgren** [comment]
@frozzare Could we tag this commit with v1.1 (or v1.1.0) to facilitate semver handling using a tool like `dep`?

**Comment by frozzare** [comment]
@HaraldNordgren done https://github.com/frozzare/go-swish/releases/tag/v1.1.0

**Pull request merged**
